// <auto-generated />
using System;
using LifeTrigger.Engine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeTrigger.Engine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308120000_AddEvaluationStatus")]
    partial class AddEvaluationStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeTrigger.Engine.Domain.Entities.EvaluationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedByUserId");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RuleSetVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Evaluations_CreatedByUserId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Evaluations_TenantId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_Evaluations_Timestamp");

                    b.ToTable("Evaluations", (string)null);
                });

            modelBuilder.Entity("LifeTrigger.Engine.Domain.Entities.TenantSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EmergencyFundBufferMonths")
                        .HasColumnType("integer");

                    b.Property<int>("IncomeReplacementYearsSingle")
                        .HasColumnType("integer");

                    b.Property<int>("IncomeReplacementYearsWithDependents")
                        .HasColumnType("integer");

                    b.Property<decimal>("InventoryRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaxIncomeReplacementYears")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxTotalCoverageMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MinCoverageAnnualIncomeMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("TenantId");

                    b.ToTable("TenantSettings", (string)null);
                });

            modelBuilder.Entity("LifeTrigger.Engine.Infrastructure.Entities.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAt");

                    b.ToTable("IdempotencyKeys", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
